##### Importando Dados

In [1]:
import pandas as pd
import numpy as np

ENDERECO_DADOS = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'

##### Lendos os dados

In [ ]:
try:
    df_roubos = pd.read_csv(ENDERECO_DADOS, sep= ';', encoding='iso-8859-1')
    # display(df_roubos)
    # display(df_roubos.columns)
    display(df_roubos['regiao'].unique())
    # display(df_roubos.head())

except Exception as e:
    print(f"An error occurred: {e}")

##### Demilitando as variaveis

In [22]:
try:
    df_roubos = df_roubos[['cisp', 'regiao', 'munic', 'roubo_veiculo']]

    df_correcao_acentuacao = df_roubos['regiao'].str.startswith('Grande Niter', na=False)
    # display(df_correcao_acentuacao)

    # Grava Grande Niterói na posição onde for encontrada
    df_roubos.loc[df_correcao_acentuacao, 'regiao'] = 'Grande Niterói'
    # display(df_roubos['regiao'].unique())

    # Agrupando por cisp, regiao e munic
    df_roubo = df_roubos.groupby(['cisp', 'regiao', 'munic'], as_index= False)['roubo_veiculo'].sum()

    display(df_roubo)

except Exception as e:
    print(f'Erro ao limpar os dados: {e}')

     cisp    regiao                 munic  roubo_veiculo
0       1   Capital        Rio de Janeiro            582
1       4   Capital        Rio de Janeiro           2220
2       5   Capital        Rio de Janeiro           1373
3       6   Capital        Rio de Janeiro           4678
4       7   Capital        Rio de Janeiro           2030
..    ...       ...                   ...            ...
141   159  Interior  Cachoeiras de Macacu            286
142   165  Interior           Mangaratiba            502
143   166  Interior        Angra dos Reis            972
144   167  Interior                Paraty            106
145   168  Interior             Rio Claro             65

[146 rows x 4 columns]

##### Processando as informações

In [23]:
try:

    array_roubos = np.array(df_roubo['roubo_veiculo'])

    media = np.mean(array_roubos)
    mediana = np.median(array_roubos)
    total = np.sum(array_roubos)

    # obtendo os quartis
    q1 = np.quantile(array_roubos, 0.25)
    q3 = np.quantile(array_roubos, 0.75)

    print('##### MEDIDAS ######')
    print(f'Média: {media}')
    print(f'Mediana: {mediana}')
    print(f'Total: {total}')
    print(f'Q1: {q1}')
    print(f'Q3: {q3}')

except Exception as e:
    print(f'Erro ao processar as informações: {e}')

##### MEDIDAS ######
Média: 4972.246575342466
Mediana: 954.0
Total: 725948
Q1: 94.75
Q3: 7371.5

##### Criando a coluna Flag

In [24]:
try:

    # Maiores
    df_maiores = df_roubo[df_roubo['roubo_veiculo'] > q3].copy()
    df_maiores['flag'] = 'Maiores'

    # Menores
    df_menores = df_roubo[df_roubo['roubo_veiculo'] < q1].copy()
    df_menores['flag'] = 'Menores'

    # Concatenando os DataFrames
    df_roubos_flag = pd.concat([df_maiores, df_menores], ignore_index=True)
    display(df_roubos_flag)

except Exception as e:
    print(f'Erro ao criar a coluna flag: {e}')

    cisp    regiao                  munic  roubo_veiculo     flag
0     17   Capital         Rio de Janeiro           7750  Maiores
1     20   Capital         Rio de Janeiro           9133  Maiores
2     21   Capital         Rio de Janeiro          19818  Maiores
3     22   Capital         Rio de Janeiro          15200  Maiores
4     23   Capital         Rio de Janeiro          10803  Maiores
..   ...       ...                    ...            ...      ...
69   155  Interior  São Sebastião do Alto             29  Menores
70   156  Interior   Santa Maria Madalena             47  Menores
71   157  Interior      Trajano de Morais             21  Menores
72   158  Interior             Bom Jardim             21  Menores
73   168  Interior              Rio Claro             65  Menores

[74 rows x 5 columns]

##### Exportando como CSV e/ou XLSX

In [25]:
try:

    df_roubos_flag.to_csv('roubos_veiculos.csv', index=False)
    df_roubos_flag.to_excel('roubos_veiculos.xlsx', index=False)
    print('DataFrame exportado com sucesso!')


except Exception as e:
    print(f'Erro ao exportar dados: {e}')

DataFrame exportado com sucesso!